Welcome Modal
breatheco-de/app pull request #1081
Opened 2023-09-04 17:52 UTC by ArielCalisaya

>PR created for issue [Mostrar modal introductoria a 4Geeks #5847](https://github.com/breatheco-de/breatheco-de/issues/5847)

2023-09-05 22:22 UTC, alesanchezr commented
#### 📝 Changed routes:


| [**…Slug\]/\[slug\]/\[version\]**](https://app-hk8urfgel-geeksacademy.vercel.app/cohort/[cohortSlug]/[slug]/[version]) | [**/lesson/\[slug\]**](https://app-hk8urfgel-geeksacademy.vercel.app/lesson/[slug]) |
|:-:|:-:|
|<a href="https://app-hk8urfgel-geeksacademy.vercel.app/cohort/[cohortSlug]/[slug]/[version]"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/ZxilVKbh8wQlxpGXtzL6gDAqOC5ajzS9tC7pQfqvhLYoeEs5UqxyHUCQhO5KcANihLlg0B-IHRg_eucDNb5cUA.png&w=600" alt="Screenshot of /cohort/[cohortSlug]/[slug]/[version]" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/VGwuBsfLwMW6iTD5xEE-neLE-AcfgCn1tEke-bVRM4wmZlz1jThXKLk6HEjy7fYBWCzs0puRFAoaaR7NWcXreQ.png">(view full size)</a> |<a href="https://app-hk8urfgel-geeksacademy.vercel.app/lesson/[slug]"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/WwaFclSvo8EBB3r3WCoh4lAyV6hNdWBwVbXt594K09wlbmCGouwZ_zaqp2EV83yK9FFqhc8qFXBIzU9tvr-TmA.png&w=600" alt="Screenshot of /lesson/[slug]" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/dD5crSk38rkkcxAw2Cq3KuNQdPtItXxDlLl0NPXkMKiOQB90732abRU2MTUv-w0dHYaYjcz0oxFcJNKKjGd3UA.png">(view full size)</a> |







Commit 9014f909bbeb42a2d5bc8d25fe0a0844ca698c7b (https://app-hk8urfgel-geeksacademy.vercel.app).

2023-09-06 20:19 UTC, tommygonzaleza approved these changes

2023-09-21 15:31 UTC, tommygonzaleza requested changes

2023-09-21 15:31 UTC, tommygonzaleza commented on scripts/redirects-generator.js
> +    academy: WHITE_LABEL_ACADEMY,
Que pasaria aca si WHITE_LABEL_ACADEMY contiene varias academias? El backend permite recibir varias academias por el header?

2023-09-21 15:45 UTC, merged