changes in time
breatheco-de/app pull request #1659
Opened 2024-10-23 22:47 UTC by lumi-tip

### Issue: https://github.com/breatheco-de/breatheco-de/issues/7872

2024-10-24 07:30 UTC, tommygonzaleza approved these changes

2024-10-24 18:16 UTC, alesanchezr requested changes

2024-10-24 18:16 UTC, alesanchezr commented on src/common/components/Timer.jsx
> +        {/* {autoRemove && timer?.months <= 0 ? null : `${timer?.months} ${Number(timer?.months) === 1 ? t('word-connector.month') : t('word-connector.months')} `} */}
porque dejaste esto comentado?? Dile no al malandreo.

2024-10-29 11:23 UTC, tommygonzaleza approved these changes

2024-11-04 19:02 UTC, tommygonzaleza approved these changes

2024-11-04 19:11 UTC, merged