Breathe code app /choose page
breatheco-de/app pull request #25
Opened 2021-09-22 23:29 UTC by moldovanjason

Finished /choose page with chakra.ui

2021-09-23 21:54 UTC, moldovanjason commented
no more errors

2021-09-28 19:55 UTC, ArielCalisaya requested changes

2021-09-28 19:55 UTC, ArielCalisaya commented on src/pages/choose-program.jsx
> +        <Text fontSize={['10px', '15px', '15px', '20px']} margin="0px" color="blue.400" fontWeight="800" justifyContent="center" alignContent="center" alignItem="center" marginRight="15px">
You are using the `Text` component even to use it as `Div` or container, I also don't see that you use the `Heading` component to differentiate between title or subtitles or `Box` component (works like Div)

### Preview of multiple `p` tags generated by `Text` component
![Screenshot from 2021-09-28 16-50-29](https://user-images.githubusercontent.com/51676628/135156474-b474c30c-141c-41e4-a494-237df19256c1.png)

2021-09-30 23:23 UTC, alesanchezr approved these changes

2021-10-04 16:51 UTC, ArielCalisaya approved these changes

2021-10-05 19:18 UTC, merged