Component complete
breatheco-de/app pull request #5
Opened 2021-08-04 01:44 UTC by amafjarkasi

https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/1624

2021-08-04 02:03 UTC, ArielCalisaya requested changes

2021-08-04 02:03 UTC, ArielCalisaya commented on src/common/components/supportSidebar.jsx
> +/* eslint-disable no-console */
you need to adapt to the eslint rules, remove these comment lines and fix the eslint warns

2021-08-04 02:21 UTC, amafjarkasi commented on src/common/components/Icon/set/arrowright.jsx
> +const arrowright = () => (
all changes should be fixed

2021-08-04 02:54 UTC, ArielCalisaya approved these changes

2021-08-09 17:45 UTC, amafjarkasi commented
I added arguments to component - please review if correct

2021-08-10 17:46 UTC, ArielCalisaya approved these changes

2021-08-17 21:29 UTC, ArielCalisaya approved these changes

2021-08-17 22:28 UTC, ArielCalisaya approved these changes

2021-08-17 22:28 UTC, merged