Landing for technologies
breatheco-de/app pull request #645
Opened 2023-02-07 02:47 UTC by ArielCalisaya

>PR created for issue [Create a quick landing for technologies #4326](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4326)

2023-02-07 02:54 UTC, alesanchezr commented
#### 📝 Changed routes:


| [**/how-to**](https://app-cxwjzitn3-geeksacademy.vercel.app/how-to) | [**/technology/\[slug\]**](https://app-cxwjzitn3-geeksacademy.vercel.app/technology/[slug]) |
|:-:|:-:|
|<a href="https://app-cxwjzitn3-geeksacademy.vercel.app/how-to"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/NdO392DFf1BDUFU1bkLTuiTLLZCoY9MyfDTSCT1St1ibI-m7p8jPTbnuHneDG54kXjPsZZ8Cph_BzRVNcr_Lpg.png&w=600" alt="Screenshot of /how-to" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/KQpBBsSuOYBXx9YMPY9tUH08v8Z9MWfeILDMF1l3HNxsx9zfo7TQieOPFY8U6KbsrCZq0fGxEeAUuz7mYDpuzA.png">(view full size)</a> |<a href="https://app-cxwjzitn3-geeksacademy.vercel.app/technology/[slug]"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/sM2ZaWDHdkL2C2sHUsy7WnJ8fgZ0x2I-1d-9CgqmbbYIq7IP3f-lQGQVa1iP__Vy6V-oo7Z1Cy1CrS6Vnz3inQ.png&w=600" alt="Screenshot of /technology/[slug]" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/jDPE1e0Ex5W4dXAQ3AJrH9_s4JV3_LpXUW1It8Z6XlZ54B9t2Mm2NZWVu3ubvXWhv2ZxrTi2BRfcgIl5MJ9Oug.png">(view full size)</a> |







Commit c262c1a3227fba3596252493dccceb6d8fb7411e (https://app-cxwjzitn3-geeksacademy.vercel.app).

2023-02-07 17:13 UTC, tommygonzaleza requested changes

2023-02-07 17:13 UTC, tommygonzaleza commented on src/pages/technology/[slug].jsx
> +  const responseLessonsList = await fetch(`${process.env.BREATHECODE_HOST}/v1/registry/asset?asset_type=lesson&limit=1000`);
No have falta filtrar por cada y hacer un request diferente para cada uno. Si tu haces el request sin especificar asset_type, entonces se va a traer todos sin filtrar

2023-02-14 16:24 UTC, tommygonzaleza approved these changes

2023-02-14 16:26 UTC, merged