Development
breatheco-de/app pull request #987
Opened 2023-07-14 15:47 UTC by aayalapalacin

2023-07-14 20:15 UTC, tommygonzaleza requested changes

2023-07-14 20:15 UTC, tommygonzaleza commented on src/common/components/MarkDownParser/Quote.jsx
> +const Quote = ({ children, ...props }) => {
We should have the 4 versions provided in the design, the version used will be randomly selected

2023-07-14 20:15 UTC, tommygonzaleza commented on src/common/components/MarkDownParser/Quote.jsx
> +const Quote = ({ children, ...props }) => {
You have to create each of the component's version

2023-07-16 19:11 UTC, alesanchezr commented
#### 📝 Changed routes:


| [**…Slug\]/\[slug\]/\[version\]**](https://app-ajly9aqog-geeksacademy.vercel.app/cohort/[cohortSlug]/[slug]/[version]) | [**…active-exercise/\[slug\]**](https://app-ajly9aqog-geeksacademy.vercel.app/interactive-exercise/[slug]) |
|:-:|:-:|
|<a href="https://app-ajly9aqog-geeksacademy.vercel.app/cohort/[cohortSlug]/[slug]/[version]"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/v5UnUhbU-33-XJDk-X6_vF08QzL-l6n2T_EA_7nTIsDB3pcvdUTwqY5AqS6oSmL8m5tk49v43VojkooA0Ujwhw.png&w=600" alt="Screenshot of /cohort/[cohortSlug]/[slug]/[version]" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/pVS6jqvjPizFIsb8KFI_8uQ8Kq7XqYPB-RKjpQQBq1eVZ-FugRQBBLwYINWlLGXxAtb-VDFlo4MdJ8ULrsQWEA.png">(view full size)</a> |<a href="https://app-ajly9aqog-geeksacademy.vercel.app/interactive-exercise/[slug]"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/ef2lG1alK16n_dFC1vU3lVdOBCRRO8Lp3XZb0vAh1rDgVms6wU6UamkKBTzLw9Oa6NYDc6-Y9UBozuFn3oHzRg.png&w=600" alt="Screenshot of /interactive-exercise/[slug]" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/M3lp0l4m11ZFgdD8rJvgSJzP6tALxm4EDOxBiKIfRY-JIrgs7AUH-Gh82oeqgKnu2VsAsEOKiVZ6se_uwmBw-A.png">(view full size)</a> |



| [**/mentorship**](https://app-ajly9aqog-geeksacademy.vercel.app/mentorship) | [**…/\[lesson\]/\[lessonSlug\]**](https://app-ajly9aqog-geeksacademy.vercel.app/syllabus/[cohortSlug]/[lesson]/[lessonSlug]) |
|:-:|:-:|
|<a href="https://app-ajly9aqog-geeksacademy.vercel.app/mentorship"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/D0OI5iQS8Y_tgg52utu42KRe2ZPNgE3xU1IC_4n8nExw5ONnnx6b2Oaw1IIK7Y9M2QlRp7YuhYnzuH2mBgir0g.png&w=600" alt="Screenshot of /mentorship" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/z6UAsevRPXppTqL7y9PbP2LfdnDC3ylRZd13bdqBowmBXP1ba13x-MyhR_d_pVonH40y9AkpN81s0U4Sts7ZuA.png">(view full size)</a> |<a href="https://app-ajly9aqog-geeksacademy.vercel.app/syllabus/[cohortSlug]/[lesson]/[lessonSlug]"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/YbqM-8A-bVUD-bPt7CNmxge6Jdq48ZTsTTgno1pjAmxMqw0qwelQrUb2roLqq9nU_rCY760QP1eMgBcODv7lnA.png&w=600" alt="Screenshot of /syllabus/[cohortSlug]/[lesson]/[lessonSlug]" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/20vRfFogvFrTaeVzudbQLPww3zHx9dgY_YJ9bYcLhykNt5_oKhkzPeMRnYNDraJl6lH9YBtYITk4zYo29objdQ.png">(view full size)</a> |



| [**/workshops/\[event_slug\]**](https://app-ajly9aqog-geeksacademy.vercel.app/workshops/[event_slug]) |
|:-:|
|<a href="https://app-ajly9aqog-geeksacademy.vercel.app/workshops/[event_slug]"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/_Ab32DfI4uGFUU4UnKDmpto0UoigtANOdyo9O7TMsIhxihUoDd-BaxujqYZOmtVzuTZete09yd3PX2o97vlZXg.png&w=600" alt="Screenshot of /workshops/[event_slug]" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/Ry77rk4rBitUyjGJP3uvBiJvfZEX7OoV1TwAJsSX5MVrhngB5L1DZ4MMuWtWxQ-PAOhbN_UqJkJus2Ol8Sjbcg.png">(view full size)</a> |







Commit adbdf70eef8ad228835492c21611946b40f0de38 (https://app-ajly9aqog-geeksacademy.vercel.app).

2023-07-25 18:46 UTC, tommygonzaleza approved these changes

2023-08-01 19:44 UTC, tommygonzaleza approved these changes

2023-08-01 19:44 UTC, merged